import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Sidebar from "../components/sidebar/Sidebar";
import { learnersSidebarEntries, tutorsSidebarEntries } from "../data";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <section className="flex h-screen w-screen">
      <Sidebar sidebarEntries={tutorsSidebarEntries} />
      <div className="container p-10 w-[80%] h-screen overflow-y-auto">
        {children}
      </div>
    </section>
  );
}
